In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from os import listdir
from os.path import isfile, join, splitext

In [2]:
voci = ['Spesa_1', 'Spesa_2', 'Spesa_3', 'Spesa_4', 'Spesa_5',
        'Spesa_6', 'Spesa_7', 'Spesa_8', 'Spesa_9', 'Spesa_10',
        'Spesa_11', 'Spesa_12', 'Spesa_TOT']
spesa_col = pd.Series(voci)
iregmap = {
    1 : "PIEMONTE", 2 : "VALLE_AOSTA", 3 : "LOMBARDIA", 4 : "TRENTINO", 5 : "VENETO",
    6 : "FRIULI", 7 : "LIGURIA", 8 : "EMILIA_ROMAGNA", 9 : "TOSCANA", 10 : "UMBRIA",
    11 : "MARCHE", 12 : "LAZIO", 13 : "ABRUZZO", 14 : "MOLISE", 15 : "CAMPANIA", 16 : "PUGLIA",
    17 : "BASILICATA", 18 : "CALABRIA", 19 : "SICILIA", 20 : "SARDEGNA"
}

In [3]:
years = list(xrange(1997, 2017 + 1))

### Dati per tutta l'Italia

Qui produco il file ITALIA.csv con i dati di tutta Italia in [1997, 2017].

In [4]:
# Dati complessivi per l'Italia per ciascun anno.
main = pd.read_csv('ITALIA/Quadro_Italia_CSV.csv', sep=';', decimal=",")
reddito = pd.read_csv('ITALIA/reddito_medio.csv')
reddito = reddito[reddito.Anno >= 1997].reset_index(drop=True)
main['Reddito'] = reddito['Reddito']
main.set_index('Anno')
main.to_csv('ITALIA/ITALIA.csv', index=False)
main

,Anno,Spesa_1,Spesa_2,Spesa_3,Spesa_4,Spesa_5,Spesa_6,Spesa_7,Spesa_8,Spesa_9,Spesa_10,Spesa_11,Spesa_12,Spesa_TOT,Reddito
0,1997,390.66,39.69,149.53,603.35,126.58,101.44,268.60,66.76,147.68,11.70,98.41,181.35,2185.75,2873.69
1,1998,390.34,40.46,149.40,614.25,123.54,105.45,274.45,71.63,148.74,11.00,99.89,190.40,2219.55,2911.01
2,1999,385.92,39.65,149.58,626.20,126.77,101.98,278.35,74.72,145.48,11.60,101.95,190.12,2232.32,2904.65
3,2000,392.97,39.30,152.22,653.10,151.21,98.22,286.29,80.92,160.77,11.67,114.05,187.94,2328.66,2898.29
4,2001,399.99,38.67,160.39,681.44,138.53,92.46,271.49,74.49,148.04,10.80,120.55,194.80,2331.65,2897.30
5,2002,412.88,38.72,153.95,724.09,132.38,94.47,258.84,73.65,142.06,9.29,114.46,193.50,2348.29,2896.31
6,2003,436.36,41.46,158.96,763.98,132.35,99.59,261.19,78.47,146.33,10.82,122.75,208.59,2460.85,2918.88
7,2004,440.96,42.56,161.30,807.62,137.41,102.84,276.14,81.15,150.13,12.37,122.74,214.07,2549.29,2941.45
8,2005,443.52,43.99,156.72,829.36,134.80,102.82,283.37,80.87,146.33,10.53,126.03,214.71,2573.05,2978.53
9,2006,455.31,43.54,160.84,858.26,131.37,96.84,299.83,81.78,150.71,11.94,129.07,214.16,2633.65,3015.60
10,2007,452.98,44.57,159.79,876.44,128.95,113.05,300.11,81.40,147.19,11.26,126.10,206.84,2648.68,2954.04
11,2008,462.33,44.71,152.30,898.13,119.88,107.63,292.44,81.43,142.49,10.53,127.48,208.71,2648.06,2892.48
12,2009,445.67,41.99,143.76,916.56,117.49,98.78,272.58,77.40,135.70,10.44,129.32,202.32,2592.01,2901.02
13,2010,448.85,44.49,144.37,922.74,118.15,101.41,273.49,77.02,139.91,11.16,126.11,196.34,2604.04,2909.56
14,2011,459.57,44.83,136.74,945.62,112.98,103.41,285.09,74.25,138.20,12.15,129.28,197.77,2639.89,2731.14
15,2012,447.12,43.50,120.81,932.04,102.32,98.48,278.78,73.04,126.94,12.58,123.70,190.93,2550.24,2552.71
16,2013,439.39,42.58,109.79,920.04,93.14,95.63,259.63,69.54,120.64,11.69,119.23,189.78,2471.08,2551.27
17,2014,436.06,43.31,114.41,912.84,102.13,109.45,256.85,65.66,121.38,14.07,110.26,202.07,2488.50,2549.82
18,2015,441.50,44.09,115.81,902.54,104.34,112.72,265.59,62.88,126.41,14.78,122.39,186.32,2499.37,2554.69
19,2016,447.96,44.97,118.26,902.72,107.01,113.65,271.27,62.14,130.06,14.76,128.25,183.32,2524.38,2559.56
20,2017,457.12,45.20,119.33,898.19,109.87,122.71,290.48,63.68,129.74,16.03,130.59,181.00,2563.94,2559.56

<hr>

### Dati per regione

Qui produco un file per ogni regione, con tutti i dati dal 1997 al 2017.

mypath = './ANNO/'
# Obtain the list of all CSV files.
csvfiles = [f for f in listdir(mypath) if (isfile(join(mypath, f)) and (splitext(f))[1] == '.csv')]
csvfiles

In [5]:
# Genera un file CSV per ciascuna regione con i dati dal 1997 al 2017.
p = None
for region in iregmap.itervalues():
    x = pd.read_csv('ANNO/SOURCE/' + region + '.csv')
    y = pd.read_csv('REDDITO_PER_REGIONE/' + region + '.csv')
    y = y[y.Anno >= 1997].reset_index(drop=True)
    x = ((x.drop([1])).drop(labels=['VUOTA'], axis=1)).reset_index(drop=True)
    x['SPESA'] = spesa_col
    x = x.T
    x = x.drop(x.index[0])
    x.columns = spesa_col
    x = x.reset_index()
    x['Reddito'] = y['Reddito']
    x.rename(columns={'index' : 'Anno'}, inplace=True)
    #x = (x.set_index('SPESA')).T
    #x = x.rename_axis('Anno', axis=1)
    p = x
    x.to_csv('./REGIONE/' + region + '.csv', header=True, index=False, float_format='%.2f')#, index_label='Anno')
p

,Anno,Spesa_1,Spesa_2,Spesa_3,Spesa_4,Spesa_5,Spesa_6,Spesa_7,Spesa_8,Spesa_9,Spesa_10,Spesa_11,Spesa_12,Spesa_TOT,Reddito
0,1997,475.59,53.1,110.95,553.81,186.6,79.77,287.67,71.36,142.16,27.32,146.67,213.11,2348.11,2470.514160
1,1998,469.07,47.66,95.56,509.64,156.16,99.94,227.5,72.42,126.83,27.57,122.64,207.03,2162.02,2536.632777
2,1999,476.2,44.58,106.62,506.55,179.67,93.49,270.96,80.29,122.46,18.38,136.15,205.3,2240.65,2579.267786
3,2000,472.15,46.42,110.13,512.27,254.23,74.71,279.24,86.4,158.24,24.36,145.85,215.36,2379.36,2621.902796
4,2001,486.66,42.48,101.81,546.15,205.19,77.24,249.46,76.98,139.4,18.51,138.39,203.84,2286.11,2620.388982
5,2002,522.17,44.65,108.75,574.98,186.82,89.87,271.59,82.46,142.57,36.51,161.47,225.09,2446.93,2618.875168
6,2003,551.66,50.33,133.63,643.22,223.75,76.4,281.51,84.11,154.25,28.05,180.63,241.83,2649.37,2588.790006
7,2004,528.04,49.62,132.85,614,242.26,89.34,301.69,88.85,162.2,28.16,175.08,257.98,2670.07,2558.704844
8,2005,534.55,51.71,121.82,637.57,215.14,90.76,284.66,84.61,139.16,25.04,195.83,228.36,2609.21,2591.695854
9,2006,540.17,55.29,118.7,687.27,177.04,95.31,341.73,88.45,135.58,31.13,174.49,244.44,2689.6,2624.686863
10,2007,516.38,46.3,106.09,705.07,146.69,84.48,274.23,82.04,123.57,24.86,147.28,226.08,2483.07,2503.374292
11,2008,561.08,50.49,116.17,729.22,136.4,86.64,268.63,77.18,115.73,14.46,150.51,227.73,2534.24,2382.061721
12,2009,495.43,40.6,101.97,689.36,108.7,83.7,185.55,68.82,96.52,18.96,130.72,211.07,2231.4,2429.015681
13,2010,493.71,48.26,122.27,703.04,106.21,78.23,203.71,72.32,100.69,16.18,163.17,188.23,2296.02,2475.969641
14,2011,558.23,47.24,108.59,716.58,120.92,77.17,199.44,73.16,91.73,30.63,162.51,172.78,2358.98,2382.636659
15,2012,507.84,40.96,92.15,818.63,104.21,81.36,209.38,71.61,75.58,12.44,112.18,161.46,2287.8,2289.303677
16,2013,489.06,38.46,74.64,756.29,97.67,63.89,229.33,61.72,74.53,14.52,70.24,155.63,2125.98,2284.992912
17,2014,417.28,39.13,77.91,777.18,94.17,68.33,258.5,55.92,95.59,7.9,71.88,171.37,2135.17,2280.682147
18,2015,413.49,36.9,77.13,751.61,90.14,68.88,251.97,46.03,94.96,7.57,82.1,162.88,2083.66,2186.468961
19,2016,431.44,49.21,79.72,752.36,76.35,80.15,254.52,58.34,112.61,11.8,82.64,139.59,2128.72,2092.255774
20,2017,441.56,40.13,82.49,758.83,120.49,87.37,216.39,53.55,88.24,8.22,66.64,131.99,2095.91,2092.255774

<hr>

### Dati per anno

Una volta prodotti i dati per regione, posso ricavare quelli per anno.

In [6]:
voci_full = voci + ['Reddito']

In [7]:
df = pd.read_csv('./REGIONE/PIEMONTE.csv')
df

,Anno,Spesa_1,Spesa_2,Spesa_3,Spesa_4,Spesa_5,Spesa_6,Spesa_7,Spesa_8,Spesa_9,Spesa_10,Spesa_11,Spesa_12,Spesa_TOT,Reddito
0,1997,365.04,43.26,132.77,609.45,89.77,103.41,244.95,68.69,138.85,7.01,104.21,155.41,2062.82,2774.39
1,1998,355.96,48.53,145.11,643.26,102.21,111.18,262.67,77.45,138.72,4.69,97.37,154.36,2141.51,2762.16
2,1999,368.60,48.49,138.06,667.83,123.29,110.53,304.98,83.48,139.48,7.03,114.49,162.64,2268.90,2898.67
3,2000,365.23,42.57,148.74,714.73,136.50,92.89,325.93,90.57,172.02,6.04,112.27,165.18,2372.67,3035.18
4,2001,371.98,42.20,130.80,742.40,114.74,90.86,298.64,76.52,131.87,6.58,105.66,157.04,2269.29,3029.59
5,2002,369.58,43.92,137.00,764.64,103.59,92.54,275.38,76.03,131.47,3.33,124.27,157.47,2279.22,3024.00
6,2003,396.39,46.35,147.36,814.83,98.24,105.87,264.22,84.02,138.58,6.91,116.41,161.47,2380.65,2967.04
7,2004,416.33,49.63,163.59,903.46,142.80,121.46,312.34,89.97,147.44,8.36,121.53,197.19,2674.10,2910.09
8,2005,419.33,50.21,122.78,868.56,104.22,108.20,284.85,85.37,134.49,5.84,120.32,174.14,2478.31,2883.80
9,2006,426.34,46.83,169.20,896.22,111.21,112.96,336.03,85.87,148.64,6.39,147.43,193.42,2680.54,2857.51
10,2007,435.06,48.86,165.33,952.90,131.02,133.59,301.85,90.19,151.44,8.00,142.60,193.48,2754.32,2869.19
11,2008,442.35,50.06,143.10,982.43,93.63,111.97,295.76,87.77,148.72,4.92,155.82,167.32,2683.85,2880.86
12,2009,444.83,50.09,125.98,975.83,113.22,95.99,256.49,87.88,143.31,7.98,143.44,176.22,2621.26,2804.90
13,2010,440.62,52.16,135.62,1014.55,122.72,103.20,286.13,85.47,150.70,8.86,144.57,186.41,2731.01,2728.94
14,2011,447.04,58.97,132.73,1061.74,105.89,93.43,300.89,80.11,154.12,8.32,143.49,184.58,2771.31,2440.27
15,2012,433.85,48.23,121.96,988.80,93.48,100.24,316.84,74.72,135.47,5.62,143.59,174.86,2637.66,2151.60
16,2013,456.89,49.88,114.66,1008.06,90.34,107.87,270.91,73.77,129.38,7.41,135.63,189.91,2634.71,2294.84
17,2014,455.66,44.24,115.45,981.40,99.38,115.45,285.96,63.39,146.41,12.84,134.75,201.96,2656.89,2438.07
18,2015,462.29,45.87,108.05,957.94,95.75,117.92,276.41,64.20,144.40,11.69,150.05,187.07,2621.64,2462.31
19,2016,522.16,48.75,117.49,856.90,110.18,122.53,266.86,61.55,141.79,13.67,156.39,189.30,2607.58,2486.55
20,2017,478.46,45.34,117.62,906.49,108.92,117.56,313.20,62.58,156.81,16.15,151.70,174.17,2648.99,2486.55

In [8]:
p = None
sorted_regions = []
for region in iregmap.itervalues(): sorted_regions.append(region)
sorted_regions = sorted(sorted_regions)
for y in years:
    result = pd.DataFrame()
    result['SPESA'] = pd.Series(voci_full)
    result = result.set_index('SPESA')
    for region in sorted_regions:
        df = pd.read_csv('./REGIONE/' + region + '.csv')
        df = df.set_index('Anno')
        result[region] = df.loc[y]
    p = result
    result.to_csv('./ANNO/' + str(y) + '.csv')

# Dai dati per regione ricavo quelli per anno.
path = './REGIONE/'
csvs = [f for f in listdir(path) if (isfile(join(path, f)) and (splitext(f))[1] == '.csv')]
csvs = sorted(csvs)
csvs